# Generated by Django 4.0.3 on 2022-11-05 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_newsheadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsheadline',
            name='countries_affected',
            field=models.TextField(default="{'countries': ['Nowhere']}"),
        ),
        migrations.AddField(
            model_name='newsheadline',
            name='impact_score',
            field=models.SmallIntegerField(default=-1),
        ),
    ]
