# Generated by Django 4.1.2 on 2022-10-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_rename_stars_amount_review_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='empty_stars',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(max_length=200),
        ),
    ]
