# Generated by Django 4.1.2 on 2022-10-28 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_review_rating_average'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating_average',
            field=models.SmallIntegerField(),
        ),
    ]
