# Generated by Django 4.0.3 on 2022-11-08 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_newsheadline_countries_and_impact_score'),
        ('web', '0004_remove_review_rating_average_review_date'),
    ]

    operations = [
    ]
